### ISSUE TITLE
need for individual tile DEMs and DZs?

### ISSUE THREAD

**Issue by forkozi** [noaa-rsd/Q-Checker.github.io#18]
@jkspring, @klangrjt, @stephen-a-white 

I'm thinking about modifying Q-Checker to create all of the individual surfaces in memory, rather than writing each to disk.  Is there a reason why anyone would want the individual surfaces?

**Comment by jkspring** [comment]
I have no reason.  If we get the mosaic that is good for me.

**Comment by stephen-a-white** [comment]
agree.

**Comment by forkozi** [comment]
Roger that.   Thanks.  Pending some unforeseen memory issue, I'll go ahead and make that change.

**Comment by forkozi** [comment]
change made, will be in next version
